### ISSUE TITLE
Primary job  terminated normally, but 1 process returned a non-zero exit code. Per user-direction, the job has been aborted.

### ISSUE THREAD

**Issue by crabnebula83** [xstarkit/MPI_XSTAR#1]
Hi, 

I have been trying to run MPI_XSTAR, but the program is returning an error. It was able to build all the folders, but they were empty. 

The command line I used was
mpirun --mca mpi_warn_on_fork 0 -np 4 /Users/.../MPI_XSTAR-master/mpixstar 

The error log is reported below. Any idea what might cause the problem? Thanks!

-------------------------------------------------------     
run xstar2xspec on 000001 
*** Process received signal ***
Signal: Segmentation fault: 11 (11)
Signal code: Address not mapped (1)
Failing at address: 0x68
[ 0] 0   libsystem_platform.dylib            0x00007fff69200f5a _sigtramp + 26
[ 1] 0   ???                                 0x0000000000000000 0x0 + 0
[ 2] 0   libsystem_c.dylib                   0x00007fff68f7d44a fgetc + 15
[ 3] 0   mpixstar                            0x00000001046e0a60 main + 4208
[ 4] 0   libdyld.dylib                       0x00007fff68ef2015 start + 1
[ 5] 0   ???                                 0x0000000000000001 0x0 + 1
*** End of error message ***
-------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node My-computer exited on signal 11 (Segmentation fault: 11).
--------------------------------------------------------------------------

% more /Users/.../xstarerror.log 
[11 05 2019 10:48]: ERROR: Can't find ./000001/xout_step.log !

**Comment by danehkar** [comment]
mpixstar relies on the programs xstar, xstinitable, and xstar2table included in the HEADAS:

        [11 05 2019 10:48]: ERROR: Can't find ./000001/xout_step.log !

This error means that xstinitable has not run yet.  You should check xstarerror.log. There could be some errors related to not finding xstinitable and xstar2table. You should make sure that HEADAS package was correctly installed and all  the xstar-related programs (xstar, xstinitable, and xstar2table) are accessible by mpixstar. Make sure, you run the following commands for bash:

        export HEADAS=/../heasoft/x86_64-unknown-linux-gnu-libc2.12
        source $HEADAS/headas-init.sh

or for cshrc:

        setenv HEADAS /../heasoft/x86_64-unknown-linux-gnu-libc2.12
        source $HEADAS/headas-init.sh

**Comment by danehkar** [comment]
@crabnebula83
> The command line I used was
> mpirun --mca mpi_warn_on_fork 0 -np 4 /Users/.../MPI_XSTAR-master/mpixstar

This command would not work you should include all necessary args which will be passed to xstar, e.g.:

        mpirun --mca mpi_warn_on_fork 0 -np 8 ./mpixstar cfrac=0.4 \
        temperature=100. lcpres=0 pressure=0.03 spectrum='pow' \
        spectun=0 trad=-1. density=1.0e+12 densitytyp=0 \
        columnsof=1.0e+20 columntyp=2 column=1.e+24 columnnst=9 columnint=1 \
        rlrad38=1.e+6 rlogxityp=2 rlogxisof=0 rlogxi=5 rlogxinst=6 rlogxiint=0 \
        habund=1 heabund=1 liabund=0 beabund=0 babund=0 cabund=1 \
        nabund=1 oabund=1 fabund=0 neabund=1 naabund=0 mgabund=1 \
        alabund=1 siabund=1 pabund=0 sabund=1 clabund=0 arabund=1 \
        kabund=0 caabund=1 scabund=0 tiabund=0 vabund=0 crabund=1 \
        mnabund=0 feabund=1 coabund=0 niabund=1 cuabund=0 znabund=0 \
        modelname='xstar_pg1211' nsteps=10 niter=99 \
        lwrite=0 lprint=1 lstep=0 emult=0.5 taumax=5. radexp=0. \
        xeemin=0.1 critf=1.e-6 vturbi=100. npass=1 ncn2=9999
